// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAddk8kceTOBogGg4-i12UZUr7EFT06AA',
    appId: '1:380582041126:web:7ec485db76703e4b1778e7',
    messagingSenderId: '380582041126',
    projectId: 'appcontest-adc8f',
    authDomain: 'appcontest-adc8f.firebaseapp.com',
    storageBucket: 'appcontest-adc8f.firebasestorage.app',
    measurementId: 'G-77S7PYFTV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq5kZyRWamyof7DDfDi4R8YncyVp5mVuk',
    appId: '1:380582041126:android:25861830abf90bdf1778e7',
    messagingSenderId: '380582041126',
    projectId: 'appcontest-adc8f',
    storageBucket: 'appcontest-adc8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADTrX0thCqGJw2J6V3O5ya7hhjOn15CV0',
    appId: '1:380582041126:ios:163beb440eb9ce5a1778e7',
    messagingSenderId: '380582041126',
    projectId: 'appcontest-adc8f',
    storageBucket: 'appcontest-adc8f.firebasestorage.app',
    iosBundleId: 'com.example.cartNumber',
  );
}
